### ISSUE TITLE
Todo Tutorial Example 

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/sway-applications#60]
### Application Description

A simple smart contract for a `todo` which has a user interface.

### Motivation

The repository consists of end-to-end applications however tutorial applications should be added in order to walk a user through the creation process of decentralised applications.

A simple todo example should be added in `sway-applications/tutorials/todo`

### Features

- [ ] Sway Todo contract 
- [ ] Contract tests
- [ ] User interface
- [ ] Tutorial Docs
- [ ] CI: static analysis
- [ ] Update base Readme

**Comment by SwayStar123** [comment]
Closed as this app is no longer being worked on
